# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    amo.params:
        class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
        arguments:
            $parameters:
                basicHost: "%host.basic%"
                targetHost: "%host.target%"
                basicLogin: "%basic.login%"
                basicPass: "%basic.pass%"
                basicHash: "%basic.hash%"
                targetLogin: "%target.login%"
                targetPass: "%target.pass%"
                targetHash: "%target.hash%"
                dealGet: "%deal.get%"
                dealAdd: "%deal.add%"
                taskGet: "%task.get%"
                taskAdd: "%task.add%"
                contactGet: "%contact.get%"
                contactAdd: "%contact.add%"
                funnelGet: "%funnel.get%"
                funnelDelete: "%funnel.delete%"
                authPost: "%auth.post%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    AmoCrm\Request\AuthRequest:
        arguments:
          - "@amo.params"

    AmoCrm\Request\DealRequest:
        arguments:
          - "@amo.params"

    AmoCrm\Request\FunnelRequest:
        arguments:
          - "@amo.params"

    AmoCrm\Request\TaskRequest:
        arguments:
          - "@amo.params"

    AmoCrm\Request\ContactRequest:
        arguments:
          - "@amo.params"


    AmoCrm\Service\DealManager:
        arguments:
          - "@doctrine.orm.entity_manager"

    AmoCrm\Command\:
        arguments:
            - "@AmoCrm\\Service\\DealManager"
            - "@AmoCrm\\Request\\AuthRequest"
            - "@AmoCrm\\Request\\DealRequest"
            - "@AmoCrm\\Request\\FunnelRequest"
            - "@AmoCrm\\Request\\TaskRequest"
            - "@AmoCrm\\Request\\ContactRequest"
        resource: '../../src/Command/*Command.php'
        tags: ["console.command"]