# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    amo.params:
        class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
        arguments:
            $parameters:
                basicHost: "%host.basic%"
                targetHost: "%host.target%"
                basicLogin: "%basic.login%"
                basicPass: "%basic.pass%"
                basicHash: "%basic.hash%"
                targetLogin: "%target.login%"
                targetPass: "%target.pass%"
                targetHash: "%target.hash%"
                requestDeal: "%request.deal%"
                requestTask: "%request.task%"
                requestCompany: "%request.company%"
                requestNote: "%request.note%"
                requestContact: "%request.contact%"
                requestCustom: "%request.custom%"
                requestCustomer: "%request.customer%"
                funnelGet: "%funnel.get%"
                funnelAdd: "%funnel.add%"
                requestAuth: "%request.auth%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    AmoCrm\Request\AuthRequest:
        arguments:
          - "@amo.params"

    AmoCrm\Request\DealRequest:
        arguments:
          - "@amo.params"

    AmoCrm\Request\FunnelRequest:
        arguments:
          - "@amo.params"

    AmoCrm\Request\TaskRequest:
        arguments:
          - "@amo.params"

    AmoCrm\Request\ContactRequest:
        arguments:
          - "@amo.params"

    AmoCrm\Request\CompanyRequest:
        arguments:
          - "@amo.params"

    AmoCrm\Request\CustomFieldsRequest:
        arguments:
          - "@amo.params"

    AmoCrm\Request\NoteRequest:
        arguments:
          - "@amo.params"


    AmoCrm\Service\DealService:
        arguments: ~

    AmoCrm\Service\CompanyService:
        arguments: ~

    AmoCrm\Service\ContactService:
        arguments: ~

    AmoCrm\Service\TaskService:
        arguments: ~

    AmoCrm\Service\NoteService:
        arguments: ~


    AmoCrm\Manager\ServiceManager:
        arguments:
          - "@AmoCrm\\Service\\DealService"
          - "@AmoCrm\\Service\\CompanyService"
          - "@AmoCrm\\Service\\ContactService"
          - "@AmoCrm\\Service\\TaskService"
          - "@AmoCrm\\Service\\NoteService"
          - "@AmoCrm\\Request\\AuthRequest"
          - "@AmoCrm\\Request\\DealRequest"
          - "@AmoCrm\\Request\\FunnelRequest"
          - "@AmoCrm\\Request\\TaskRequest"
          - "@AmoCrm\\Request\\ContactRequest"
          - "@AmoCrm\\Request\\CompanyRequest"
          - "@AmoCrm\\Request\\CustomFieldsRequest"
          - "@AmoCrm\\Request\\NoteRequest"

    AmoCrm\Main:
        arguments:
          - "@AmoCrm\\Manager\\ServiceManager"

    AmoCrm\Command\:
        arguments:
          - "@AmoCrm\\Main"
        resource: '../../src/Command/*Command.php'
        tags: ["console.command"]