<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7TQMHKX\appApp_AppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7TQMHKX/appApp_AppKernelProdContainer.php') {
    touch(__DIR__.'/Container7TQMHKX.legacy');

    return;
}

if (!\class_exists(appApp_AppKernelProdContainer::class, false)) {
    \class_alias(\Container7TQMHKX\appApp_AppKernelProdContainer::class, appApp_AppKernelProdContainer::class, false);
}

return new \Container7TQMHKX\appApp_AppKernelProdContainer([
    'container.build_hash' => '7TQMHKX',
    'container.build_id' => 'd82d2c75',
    'container.build_time' => 1555513112,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7TQMHKX');
