<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'amo.params' shared autowired service.

return $this->privates['amo.params'] = new \Symfony\Component\DependencyInjection\ParameterBag\ParameterBag(['basicHost' => 'https://icontextall.amocrm.ru', 'targetHost' => 'https://new5832c10517fd6.amocrm.ru', 'basicLogin' => 'anya@icontext.ru', 'basicPass' => '!O3xJ*De7S2O', 'basicHash' => 'c9d172b0fee534eb6ba2899f9f05b8470c26ca6b', 'targetLogin' => 'k.samsonov@icontextgroup.ru', 'targetPass' => 'Pa$$1234', 'targetHash' => 'b85f7aac44825172bb4c1e904a84fbd8212c0350', 'dealGet' => '/api/v2/leads', 'funnelGet' => '/api/v2/pipelines', 'funnelPost' => '/private/api/v2/json/pipelines/set', 'funnelDelete' => '/private/api/v2/json/pipelines/delete', 'authPost' => '/private/api/auth.php']);
