<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AmoCrm\Request\DealRequest' shared autowired service.

include_once $this->targetDirs[3].'/src/Request/AbstractRequest.php';
include_once $this->targetDirs[3].'/src/Request/DealRequest.php';

return $this->privates['AmoCrm\Request\DealRequest'] = new \AmoCrm\Request\DealRequest(($this->privates['amo.params'] ?? $this->load('getAmo_ParamsService.php')));
